### ISSUE TITLE
試著看 docker-compose ps，看到 warning

### ISSUE THREAD

**Issue by johnnyskywalker** [solitude316/docker-php7-web#1]
<img width="1088" alt="screen shot 2018-01-07 at 9 19 59 am" src="https://user-images.githubusercontent.com/3930243/34645564-155e3f66-f38c-11e7-8901-3548329caa7f.png">

點解？

**Comment by solitude316** [comment]
已經拿掉 redis 的 configs 參數，目前尚不需要對 redis 做更深入的控制（之後再說吧）
